# Generated by Django 4.2.4 on 2023-08-18 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionproduct_time_alter_bids_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionproduct',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 18, 9, 51, 46, 140779, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='bids',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 18, 9, 51, 46, 140779, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 18, 9, 51, 46, 141840, tzinfo=datetime.timezone.utc)),
        ),
    ]
